### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by gobboo** [mprey/h1z1brawl#4]
Trying to host this on a server with Nginx

I'm using a reverse proxy with a subdomain for the server and I changed the API url in the config to that one.

Now it connects to the socket and Database HOWEVER, when I try to login, it returns me to the site perfectly fine but it doesn't get my login data.

It tries to make a request to loadAuth but on the website not the backend, however it does this if I host locally too.

Hosting locally works fine it's just on my website?

Do you have discord by any chance that I can talk to you on? :)

**Comment by gobboo** [comment]
I see it tries to create a proxy request with that endpoint to the localhost, which I changed to the server domain but it still doesn't want to work :/

**Comment by mprey** [comment]
yeah, sure, you can add me mprey#8968

**Comment by gobboo** [comment]
Done :)
